*Data Creation:**Create suitable arrays to represent students, subjects, and their marks.




In [6]:
import random

In [7]:
import numpy as np
num_stud=5
num_sub=3
marks=[[random.randint(50,100) for _ in range(num_sub)] for _ in range(num_stud)]
print(marks)
res=np.vstack((marks))
print(res)

[[63, 75, 53], [64, 87, 52], [63, 86, 70], [78, 56, 100], [54, 100, 82]]
[[ 63  75  53]
 [ 64  87  52]
 [ 63  86  70]
 [ 78  56 100]
 [ 54 100  82]]


Data Exploration:**Explore the properties of these arrays — such as their dimensions, size, and structure.

In [8]:
print("shape",res.shape)
print("size",res.size)
print("ndim",res.ndim)
print("dtype",res.dtype)


shape (5, 3)
size 15
ndim 2
dtype int64


Data Transformation:**Perform necessary reshaping and reorganization of the data to suit various operations.

In [9]:
flat_marks=res.flatten()
print("Flattend Marks:",flat_marks)

reshaped_marks=flat_marks.reshape(num_stud,num_sub)
print(reshaped_marks)

Flattend Marks: [ 63  75  53  64  87  52  63  86  70  78  56 100  54 100  82]
[[ 63  75  53]
 [ 64  87  52]
 [ 63  86  70]
 [ 78  56 100]
 [ 54 100  82]]


Data Combination:**Merge or split arrays to simulate adding new students, new subjects, or reorganizing the dataset.

In [10]:
new_student=np.array([[random.randint(50,100) for _ in range(num_sub)]])
updated_marks=np.vstack((res,new_student))
print(new_student)
print("Adding a New Student:\n",updated_marks)

new_subject=np.array([[random.randint(50,100)] for _ in range(updated_marks.shape[0])])
extended_marks=np.hstack((updated_marks,new_subject))
print("\n",new_subject)
print("Adding a New Student:\n",extended_marks)

[[ 91 100  99]]
Adding a New Student:
 [[ 63  75  53]
 [ 64  87  52]
 [ 63  86  70]
 [ 78  56 100]
 [ 54 100  82]
 [ 91 100  99]]

 [[67]
 [57]
 [62]
 [99]
 [56]
 [96]]
Adding a New Student:
 [[ 63  75  53  67]
 [ 64  87  52  57]
 [ 63  86  70  62]
 [ 78  56 100  99]
 [ 54 100  82  56]
 [ 91 100  99  96]]


Data Modification:**Apply operations to update marks, remove data, or identify unique information.

In [11]:
extended_marks[1][0]=99
print("After Updating 2nd Student's 1st Subject Marks\n",extended_marks)

removed_marks=np.delete(extended_marks,2,axis=0)
print("\nAfter Removing 3rd Student\n",removed_marks)

unique_marks=np.unique(removed_marks)
print("\nUnique Marks in Dataset\n",unique_marks)


After Updating 2nd Student's 1st Subject Marks
 [[ 63  75  53  67]
 [ 99  87  52  57]
 [ 63  86  70  62]
 [ 78  56 100  99]
 [ 54 100  82  56]
 [ 91 100  99  96]]

After Removing 3rd Student
 [[ 63  75  53  67]
 [ 99  87  52  57]
 [ 78  56 100  99]
 [ 54 100  82  56]
 [ 91 100  99  96]]

Unique Marks in Dataset
 [ 52  53  54  56  57  63  67  75  78  82  87  91  96  99 100]


Data Type Handling:**Demonstrate how the same data can exist in different data types and how changes affect results.

In [12]:
float_marks=extended_marks.astype(float)
print("Converted to Float Type\n",float_marks)
int_marks=float_marks.astype(int)
print("\nConverted Back to Type\n",int_marks)

Converted to Float Type
 [[ 63.  75.  53.  67.]
 [ 99.  87.  52.  57.]
 [ 63.  86.  70.  62.]
 [ 78.  56. 100.  99.]
 [ 54. 100.  82.  56.]
 [ 91. 100.  99.  96.]]

Converted Back to Type
 [[ 63  75  53  67]
 [ 99  87  52  57]
 [ 63  86  70  62]
 [ 78  56 100  99]
 [ 54 100  82  56]
 [ 91 100  99  96]]
